[project]
name = "hack-night-cofinder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dlt>=1.11.0",
    "weaviate-client>=4.14.4",
]
